### ISSUE TITLE
Get Unable to resolve host "apps.applozic.com" on Emulator on trying to login

### ISSUE THREAD

**Issue by piyushgupta27** [AppLozic/Custom-UI-Sample#4]
After fixing gradle issues, updating all API keys (Applozic and Google Maps), app is able to successfully run. But I keep getting the below error when trying to login via the Custom UI.

When i tried pinging the server it was unreachable as well:
```
ping apps.applozic.com
PING apps-prod-load-balancer-1193542739.us-east-1.elb.amazonaws.com (34.239.9.152): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
```

<img width="591" alt="Screen Shot 2020-07-05 at 11 45 06 PM" src="https://user-images.githubusercontent.com/13917079/86539542-f9400a00-bf1a-11ea-9a33-fcb312827b2d.png">

Please help with this as my integration is blocked because of this.

**Comment by Sunilkumarr** [comment]
@piyushgupta27 Can you try running on the real device? Not sure if your emulator is connected to wifi.

**Comment by piyushgupta27** [comment]
Thanks. Seems like a network issue on Android emulator. Thanks for the help.

Apologies for the false alarm.
